pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'python3 -m pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'pytest || true'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t flask-cicd-demo:latest .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                docker rm -f flask-container || true
                docker run -d --name flask-container -p 5000:5000 flask-cicd-demo:latest
                '''
            }
        }

    }

}