apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-cicd-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask-cicd-demo

  template:
    metadata:
      labels:
        app: flask-cicd-demo

    spec:
      containers:
      - name: flask-cicd-demo
        image: flask-cicd-demo:latest
        imagePullPolicy: Never

        ports:
        - containerPort: 5000